spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations:  file:///C:/Users/hp/OneDrive/Desktop/config-info/config-info-master/{application}
          order: 1